import { Geist } from "next/font/google";
import "./globals.css";
import Navbar from "@/Component/Navbar";
import VideoPlayerProvider from "@/Component/VideoPlayerProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${geistSans.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <VideoPlayerProvider>
          <div style={{ display: "flex", minHeight: "100vh" }}>
            <Navbar />
            <main style={{ flex: 1 }}>{children}</main>
          </div>
        </VideoPlayerProvider>
      </body>
    </html>
  );
}
