import "./globals.css";
import Navbar from "@/Component/Navbar";
import AuthGate from "@/Component/AuthGate";
import VideoPlayerProvider from "@/Component/VideoPlayerProvider";
import StudyBuddyChat from "@/Component/StudyBuddyChat";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full antialiased">
      <body className="min-h-full flex flex-col">
        <VideoPlayerProvider>
          <div style={{ display: "flex", flexDirection: "column", minHeight: "100vh" }}>
            <header style={{ display: "contents" }}>
              <Navbar />
            </header>
            <main style={{ flex: 1 }}><AuthGate>{children}</AuthGate></main>
          </div>
          <StudyBuddyChat />
        </VideoPlayerProvider>
      </body>
    </html>
  );
}
